### ISSUE TITLE
Script Editor: Cannot copy the error message

### ISSUE THREAD

**Issue by pkrasimirov** [Dwarf-Therapist/Dwarf-Therapist#109]
As a side-effect of #108 I found another problem:
The red-colored error message in Script Editor cannot be copied because it disappears as soon as the mouse leaves the code editing area.  There is no way to switch focus to the error panel without it getting blanked first.

Not a big prio but there should be better way to report errors, besides reading the error text and typing it anew, or the mighty screenshot.

**Comment by cvuchener** [comment]
Indeed, it is not a good idea to show the script execution log as a status tip. And after a quick check I did not see anything else using the status tip in the script dialog, it could be replaced with a persistent error log.

Another issue I am noting here so it is not forgotten: the error message when the script does not return a boolean always says "undefined" because of a typo in ScriptDialog::script_is_valid.
