### ISSUE TITLE
Dwarf Therapist Causing massive network ping spikes

### ISSUE THREAD

**Issue by sparksoldier** [Dwarf-Therapist/Dwarf-Therapist#183]
Lately, when I have been playing DF, I noticed that my ping would constantly spike rapidly, making it impossible to have a stable voice call with someone. After testing what programs were causing this, I concluded that it was specifically Dwarf Therapist that would cause this. Just having the program up is causing this issue, and I have already tried disabling auto updates and even tried to manually cut off the program from the internet with windows firewall. The strange part is that the program is not showing up on my resource monitor at all, so i cant find what is causing it. Is there any reason that this could be happening? Is there another way to stop dwarf therapist from doing this?
Picture included is my ping test while using the program, normal ping is in the 40s
![ping test](https://user-images.githubusercontent.com/58895997/70857227-72f9a300-1eb8-11ea-8477-33d1c966eb73.png)

**Comment by lethosor** [comment]
Sounds similar to #92 to me

**Comment by sparksoldier** [comment]
> 
> 
> Sounds similar to #92 to me

Yes, I noticed that issue earlier when looking for answers

**Comment by cvuchener** [comment]
Please add information to the existing issue instead of creating a new one.

As for the issue, it seems clear from what was reported that it is not caused my DT network usage. It may be another application (maybe an antivirus) triggered by DT hacky behavior that is causing the spikes. I cannot think of anything that DT would be doing every 8s, it is polling if a game is loaded every 1s and retrying to connect after 5s. Or maybe Qt is doing weird stuff in the back and I should try a build with no network support at all.
