### ISSUE TITLE
Dwarf-Therapist runs in terminal, but not when clicked

### ISSUE THREAD

**Issue by Jericho360** [Dwarf-Therapist/Dwarf-Therapist#254]
Using Linux Mint 20.2

Whenever I try to run dwarf therapist via doubling clicking it, it brings up the a list of applications to open it with, but when I go the folder in the terminal and use ./dwarftherapist it runs.

**Comment by cvuchener** [comment]
This is an issue with your file manager or whatever you are double-clicking.

If you want to launch dwarftherapist from GUI, you should use desktop entry file ([one](https://raw.githubusercontent.com/Dwarf-Therapist/Dwarf-Therapist/master/dist/xdg/applications/dwarftherapist.desktop) is provided in this repository). How did you install Dwarf Therapist? If you installed it to a standard prefix like /usr/local or ~/.local, it should automatically show up in your application launcher. Otherwise, you can use MenuLibre for creating custom desktop entries from a GUI.

**Comment by Jericho360** [comment]
It went to the standard /usr/local etc. location. It does appear on my application manager. Thank you for your help!
