### ISSUE TITLE
Feature request: Legalize child labor

### ISSUE THREAD

**Issue by robob27** [Dwarf-Therapist/Dwarf-Therapist#265]
As of DF 50 children are now ~~allowed~~ forced to do 14 types of labor:

![image](https://user-images.githubusercontent.com/2104555/207746369-49e2237f-d2b5-47d3-9a46-66426fd0190d.png)

We can do this in DT currently, but have to use the "Allow Labor Setting on Anyone" option under the "I'm a Dirty Cheater" heading. Since child labor is legal in vanilla now, we could update this option to something like "Allow any labor for children" which would enable setting labors outside of the default 14 that children are allowed to do.

Edit: I created this issue assuming DT wants to continue to update to support classic with similar restrictions to whatever "vanilla" DF is. Please disregard if this is not the case!

**Comment by ab9rf** [comment]
i will point out that forcing children to do chores in 50.0x results in _very_ unhappy children who frequently tantrum and often go insane. i don't know if this is intentional by toady, but it probably will _not_ have the same effect in versions below 50.0x, meaning this option presents a different set of game balance issues.

obviously this is ultimately a matter of player choice. at the same time, it seems reasonable to me that tools that target 47.05 (or any other pre-50.0x version) should probably harmonize with the game mechanics of that version by default.
