### ISSUE TITLE
does not work with itch.io edition.

### ISSUE THREAD

**Issue by hajji-et-al** [Dwarf-Therapist/Dwarf-Therapist#273]

**Comment by ab9rf** [comment]
itch.io executables have different timestamps from either steam or classic, and may (generally will) have different offsets. some of the structures are also different

the dfhack team is not yet supporting itch (or classic) versions due to differences in the `gamest` structure among the three versions; presumably dt will have to offer three different .ini files, one for each edition

**Comment by cvuchener** [comment]
[The latest release](https://github.com/Dwarf-Therapist/Dwarf-Therapist/releases/tag/v42.0.0) has a memory layouts for 50.07-itch but it is untested. Please report if you any issue with it.
