### ISSUE TITLE
Satisfied Showing up as Sadness in recent events.

### ISSUE THREAD

**Issue by dgomiller** [Dwarf-Therapist/Dwarf-Therapist#274]
When viewing information, items describes as being "Satisfied" in game are described as "Sadness" in DT. See attached.

![image](https://user-images.githubusercontent.com/24719868/211371340-49c28db9-c182-4d8e-a790-ef311314cbdb.png)

![image](https://user-images.githubusercontent.com/24719868/211371629-2079577b-a3d6-4c21-b649-97dd08ff8e1d.png)

**Comment by cvuchener** [comment]
Already reported on the [forum](http://www.bay12forums.com/smf/index.php?topic=168411.msg8443249#msg8443249)

And fixed in #266 (b0dbc1023be0f4b0f23e71658b12510656ad0290)

You can update your [game_data.ini](https://raw.githubusercontent.com/cvuchener/Dwarf-Therapist/dev0.50/resources/game_data.ini) if you want it fixed.

**Comment by dgomiller** [comment]
Thank you, that worked. For those unsure what to do, put the ini in the data folder.

**Comment by cvuchener** [comment]
fixed by #266
