### ISSUE TITLE
libstdc++.so.6

### ISSUE THREAD

**Issue by jserras** [Dwarf-Therapist/Dwarf-Therapist#61]
Greetings,

I'm trying to use the AppImage you provide, but a real show stopper came up.
```
./DwarfTherapist-v39.2.1-linux-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./DwarfTherapist-v39.2.1-linux-x86_64.AppImage)
./DwarfTherapist-v39.2.1-linux-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./DwarfTherapist-v39.2.1-linux-x86_64.AppImage)
```
Unfortunately my system is supporting the previous versions GLIBCXX_3.4.20 and CXXABI_1.3.8, and updating libstdc++6 is no easy or stable task, usually it means upgrading to the next version of the distro, which is not always possible.

Could you please bundle the libstdc++6 files used with the AppImage?!
Would be nice and I'm sure it will come up eventually if not already.

Regards

João Serras

**Comment by cvuchener** [comment]
From [my experience with Dwarf Fortress](http://www.bay12forums.com/smf/index.php?topic=169148.0), bundling libstdc++ creates other issues. And the [tool](https://github.com/probonopd/linuxdeployqt) I use for creating the AppImage does not have any option to bundle these libraries.

I don't think I can build with an older ABI version because of the C++11 changes.

As a workaround, you could try [extracting](https://github.com/AppImage/AppImageKit/wiki/Extracting-AppImages) the AppImage and add the libraries from the deb packages.

I think the libraries used for building were:
 - [libgcc1 7.2.0-1ubuntu1~14.04 amd64](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/13272481/+files/libgcc1_7.2.0-1ubuntu1~14.04_amd64.deb)
 - [libstdc++6 7.2.0-1ubuntu1~14.04 amd64](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+build/13272481/+files/libstdc++6_7.2.0-1ubuntu1~14.04_amd64.deb)

**Comment by cvuchener** [comment]
Try this one: https://github.com/Dwarf-Therapist/Dwarf-Therapist/releases/download/v39.2.1/DwarfTherapist-v39.2.1-linux-x86_64-with-libstdcxx.AppImage

**Comment by jserras** [comment]
Thank you very much, the build you provided works fine.

I also came up with a personal solution, just in case.

I downloaded the libstdc++6 from the next release and extracted it beside the DT AppImage, and started DT with "LD_LIBRARY_PATH="usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH" " prepended to it, created a launch script and also works fine.

Only found this format, appimage, recently, not yet very familiar with it, just saw you can also extract it, would also work around the problem, I'm sure would be rebuildable, but if you could just target a bit older system it would great, just a current distro - 1 would solve it permanently, or whatever you think would be better, but would be great, more consistent, if the regular download supported a bit older distros.
Many distros are suffering delays in release lately, because of a certain software that is disrupting the community, you know which.
I should be able to help with it as soon as i'm more familiar with the format if needed.

Regards,

João Serras

**Comment by cvuchener** [comment]
I would not consider this solved until TravisCI build is fixed (or until every pre-gcc-5 distro is EOL).

An older distro may not help. It is currently built on Ubuntu 14.04 that ships with gcc 4.8 (older than debian jessie gcc 4.9). But I missed that when installing gcc-5, it also installs libstdc++ from gcc 7.2.0.

This issue is not present on Centos 6 (gcc 4.4), but I suspect devtoolset does some special things like partial static linking for more recent features.

The simplest solution would be to make two appimage one like the current one and the other including libstdc++ (and libgcc?) like the test one. The test appimage with libstdc++ does not work on CentOS 6: it would require libc.so too. But I don't think it has to work with CentOS 6, it is not that hard to make a special build for it, unlike Debian Jessie.

**Comment by cvuchener** [comment]
According to linuxdeployqt's author, I should use a [patched AppRun](https://github.com/darealshinji/AppImageKit-checkrt/) so the included libstdc++ is only used when necessary.

**Comment by cvuchener** [comment]
Can you try this appimage: https://framadrop.org/r/xGxX1hwSpQ#AumilXOmrjLKiiEjP2aEtKlbYqhPphMrrUgj0ecrNWo=

It is a fedora 27 build using the patched AppRun and optional .so.

**Comment by jserras** [comment]
This build is not working for me:
```
DwarfTherapist: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_Dwarf_TSEVV6/usr/lib/libpng16.so.16)
DwarfTherapist: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_Dwarf_TSEVV6/usr/lib/libsystemd.so.0)
```
I'm using devuan jessie, the libc6 is 2.19-18+deb8u10 and zlib1g is 1.2.8.dfsg-2+b1

**Comment by cvuchener** [comment]
Sorry, I was focused on libstdc++, I forgot libc issues.

https://framadrop.org/r/fTSmFizL_J#jGdcO0UALAI8gTqaOG2DrgRcjxiXZWBbMMDw505rF4s=

Here is a build from Ubuntu 14.04.

**Comment by jserras** [comment]
This is working fine yes, but have to launch with the PATH modification yes.

**Comment by cvuchener** [comment]
Did you use the link from my previous comment or the test build from the pull request? The latter should have fixed the PATH issue.

**Comment by cvuchener** [comment]
Reopen if you still have an issue after the next release.
