### ISSUE TITLE
Add beliefs and goals to roles

### ISSUE THREAD

**Issue by cvuchener** [Dwarf-Therapist/Dwarf-Therapist#87]
Split from #86.

**Comment by mnorthey** [comment]
Hey there. New to this project, but thought I'd investigate this further today. After spending some time swimming in code, I think I have a pretty good sense of what needs to be done. Happy to keep plugging along on this if no one else wants to grab it. No changes yet to custom role functionality, but I've added scholar as an actual role to aid in testing, so now it's showing up in the Roles tab ([fork](https://github.com/mnorthey/Dwarf-Therapist/tree/scholar-role/resources)). I figured this might get used enough by players to warrant a default option. We could also expand this easily enough to include the other occupations (performer, scholar, scribe, tavern keeper), if desired. Lastly, it's worth nothing that any modifications should not only include beliefs and goals, but also _facets_, which includes some traits that are important for scholars, like curious and abstract_inclined. (Or, alternatively, these could be lumped into one "Personality Traits" category.)

**Comment by cvuchener** [comment]
Thanks for the suggestion. I have added issue #88 for role suggestions.

> Hey there. New to this project, but thought I'd investigate this further today. After spending some time swimming in code, I think I have a pretty good sense of what needs to be done. Happy to keep plugging along on this if no one else wants to grab it. No changes yet to custom role functionality

The biggest change will be redoing the custom role dialog because it is cluttered enough without adding two more types. I was planning to do this one myself as I have already change custom roles code a lot (I should have assigned myself to be clear). And I made a mock-up some time ago for what it may look like:
![role dialog tree view mockup](https://user-images.githubusercontent.com/3874173/34649026-6dd2cb16-f3a6-11e7-8cf7-93d199cd6059.png)

> it's worth nothing that any modifications should not only include beliefs and goals, but also facets

Facets are already here, it is what is currently called "traits".

**Comment by cvuchener** [comment]
What should be the default weights for beliefs and goals? For comparison, the current default weights are:
 - Attributes: 0.25
 - Skills: 1.00
 - Facets: 0.20
 - Preferences: 0.15

**Comment by mnorthey** [comment]
> What should be the default weights for beliefs...

Based on #88 and [various](http://dwarffortresswiki.org/index.php/DF2014:Scholar) [sources](http://www.bay12forums.com/smf/index.php?topic=154895.0), it seems that certain beliefs are fairly important for Scholars, which would prompt a moderately high weight. That said, it seems that beliefs play a role for all dwarfs in [generating needs](http://dwarffortresswiki.org/index.php/DF2014:Need), which affect focus and happiness. I think it makes sense to set the default where it should be for most dwarfs even though Scholar is the only role that is currently accounting for beliefs (and possibly Scribe?). That way, implementation into existing roles will be easier in the future, though the Scholar role would need to code in custom weights. I personally haven't paid much attention to needs before, but going off what's on the Wiki, I would give beliefs the same default weight as facets, since they seem to operate in a very similar manner. 

> ...and goals?

The [Wiki](http://dwarffortresswiki.org/index.php/DF2014:Personality_trait#Goals) seems to suggest that goals may have an effect on dwarfs prior to completion, but I did a cursory search and couldn't find any confirmation of this. As far as I know, the only effect these have is to provide a happiness boost when satisfied. Based on that, my perspective would be to align the default weight with preferences.

**Comment by cvuchener** [comment]
I was going for the same values as facets and preferences too if no one had a better idea.

> The Wiki seems to suggest that goals may have an effect on dwarfs prior to completion, but I did a cursory search and couldn't find any confirmation of this. As far as I know, the only effect these have is to provide a happiness boost when satisfied.

It must be referring to dreams of immortality leading to becoming a necromancer. Other goals may affect behavior in more subtle ways, but that would be hard to confirm.

For role ratings, I am assuming there is no effect after completion, and [I am only counting unrealized goals](https://github.com/cvuchener/Dwarf-Therapist/blob/e5ac24d595c05e5b882c40fa953a102c7ba69e02/src/dwarf.cpp#L2946). It could be possible to use a different rating for matching realized goals, if it made sense.

**Comment by feelotraveller** [comment]
Not suggesting that it is any better but 0.10 was what first sprang to mind.  But I pulled that out of my... hat. :smile: 

Whatever we go for I think we should be asking for feedback/suggestions from users on the default weight.

**Comment by cvuchener** [comment]
0.10 for beliefs or goals (or both)?

The problem with choosing a value now and improving later, is that, on the first run of DT, the current value will be stored in the user settings and a new "default default value" will not be used unless the user settings are reset.

I should consider a "restore default weight" button or adding check-boxes for always using the "default default values".

**Comment by feelotraveller** [comment]
I did not realise that the default defaults could not be reset with updates, though it does make sense not to override the users settings.

Both, I was thinking, although for no real reason.  But if the default defaults are fixed how about setting  them at 0, and advise users that they will need to activate/weight them themselves?  Any other value is likely to be a bad choice in the long run since we really have no idea.

**Comment by lethosor** [comment]
Could you make the defaults depend on the DF version? What about allowing users to overwrite these settings, but not saving them to disk otherwise, so that users that don't want to override them will use whatever the defaults are in future versions?

**Comment by cvuchener** [comment]
I could do something like that:
![capture d ecran de 2018-06-11 09-28-28](https://user-images.githubusercontent.com/3874173/41218354-15fbdf34-6d5b-11e8-8db8-4c87465e5457.png)

**Comment by mnorthey** [comment]
> What about allowing users to overwrite these settings, but not saving them to disk otherwise, so that users that don't want to override them will use whatever the defaults are in future versions?

> I could do something like that:

This seems like a good compromise to me. It also makes things much easier for players who start new fortresses with every update.
